version = 0.1

[default.global.parameters]
region = "us-east-1"
stack_name = "summafy-lambdas"
s3_bucket = "summafy-artifacts"

[default.build.parameters]
cached = true
parallel = true
template_file = "template.yaml"

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = [ "CAPABILITY_IAM", "CAPABILITY_NAMED_IAM" ]
stack_name = "summafy-lambdas"
s3_bucket = "summafy-artifacts"

[default.package.parameters]
s3_bucket = "summafy-artifacts"

[default.sync.parameters]
watch = true
template_file = "template.yaml"
dependency_layer = false
s3_bucket = "summafy-artifacts"

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"


