version = 0.1

[default.global.parameters]
region = "us-east-1"
stack_name = "summafy-lambdas"

[default.build.parameters]
cached = true
parallel = true
template_file = "/home/emmaahmads/workspace/summafy_repos/lambda-sam-app/template.yaml"

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = [ "CAPABILITY_IAM", "CAPABILITY_NAMED_IAM" ]
confirm_changeset = false
resolve_s3 = true
stack_name = "summafy-lambdas"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
template_file = "/home/emmaahmads/workspace/summafy_repos/lambda-sam-app/template.yaml"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cdrzmdedc1gm"
dependency_layer = false

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
