AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DocBucketName:
    Type: String
    Description: "The name of the existing S3 bucket that triggers the Lambda"
  ZipBucketName:
    Type: String
    Description: "The S3 bucket name where the Lambda zip file is stored"

Resources:
  SummafyIngestorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "summafy-ingestor"
      PackageType: Zip
      CodeUri:
        Bucket: !Ref ZipBucketName
        Key: lambda-ingestor.zip
      Runtime: python3.9
      Handler: app.lambda_handler
      MemorySize: 512
      Timeout: 30
      Layers:
        - arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-python-amd64-ver-1-21-0:1
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - !Join [ "", [ "arn:aws:s3:::", !Ref DocBucketName ] ]
                - !Join [ "", [ "arn:aws:s3:::", !Ref DocBucketName, "/*" ] ]

Outputs:
  SummafyIngestorFunction:
    Description: Ingestor Function ARN
    Value: !GetAtt SummafyIngestorFunction.Arn
