AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  SummafyReadS3ContainerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: 120569638976.dkr.ecr.us-east-2.amazonaws.com/summafy-step/ingestor:379078b1dbdd4cce94df6189fc0958bd8d5f717c
      MemorySize: 512
      Timeout: 30
      Architectures:
        - x86_64
      Policies:
        - S3ReadPolicy:
            BucketName: superumi-summafy-123
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - arn:aws:s3:::superumi-summafy-123/*

Outputs:
  SummafyReadS3ContainerFunction:
    Description: Read S3 Container Function ARN
    Value: !GetAtt SummafyReadS3ContainerFunction.Arn

  # Gives permision to S3 bucket to invoke the lambda function created in the stack
  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SummafyReadS3Function
      Principal: s3.amazonaws.com
      SourceArn: arn:aws:s3:::superumi-summafy-123
      SourceAccount: !Ref AWS::AccountId
  
  #

  
Outputs:
  SummafyReadS3ContainerFunction:
    Description: Read S3 Container Function ARN
    Value: !GetAtt SummafyReadS3ContainerFunction.Arn

