AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DocBucketName:
    Type: String
    Description: "The S3 bucket name that the Lambda can access"
  ZipBucketName:
    Type: String
    Description: "The S3 bucket name that the Lambda zip file is stored in"

Resources:

  SummafyIngestorFunction:
    Name: "summafy-ingestor"
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri:
        Bucket: !Ref ZipBucketName
        Key: lambda-ingestor.zip
      Runtime: python3.9
      Handler: app.lambda_handler
      MemorySize: 512
      Timeout: 30
      Layers:
        - arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-python-amd64-ver-1-21-0:1
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocBucketName
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - !Sub arn:aws:s3:::${DocBucketName}/*

  S3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SummafyIngestorFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${DocBucketName}
      SourceAccount: !Ref AWS::AccountId

Outputs:
  SummafyIngestorFunction:
    Description: Ingestor Function ARN
    Value: !GetAtt SummafyIngestorFunction.Arn
