name: Deploy SAM App
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    # paths:
    #   - 'sam/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::120569638976:role/GithubAction-sam-deploy
          aws-region: us-east-1

      - name: Deploy SAM application
        working-directory: sam
        env:
          # TARGET_BUCKET_NAME: ${{ secrets.ARTIFACT_BUCKET_NAME }}
          TARGET_BUCKET_NAME: summafy-superumi123
        run: |
          sam build
          sam deploy \
            --stack-name summafy-lambdas \
            --region us-east-1 \
            --s3-bucket summafy-artifacts-70819-jalancengal-xx \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --resolve-image-repos \
            --parameter-overrides TargetBucketName=summafy-superumi123

