name: Deploy SAM App
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    # paths:
    #   - 'sam/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::120569638976:role/GithubAction-sam-deploy
          aws-region: us-east-1

      - name: Deploy SAM application
        working-directory: sam
        run: |
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --resolve-image-repos
