name: Deploy Serverless Application
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    # paths:
    #   - 'sam/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy SAM application
        working-directory: sam
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          DOC_BUCKET_NAME: ${{ secrets.DOC_BUCKET_NAME }}
          ZIP_BUCKET_NAME: ${{ secrets.ZIP_BUCKET_NAME }}
          INGESTOR_FUNCTION_ARN: arn:aws:lambda:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:function:summafy-ingestor
        run: |
          echo "Building SAM application..."
          sam build
          echo "Deploying SAM application..."
          sam deploy \
            --stack-name summafy-lambdas \
            --region $AWS_REGION \
            --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides DocBucketName=${DOC_BUCKET_NAME} ZipBucketName=${ZIP_BUCKET_NAME}
          
          echo "Adding permission to Lambda function..."
          aws lambda add-permission \
            --function-name summafy-ingestor \
            --principal s3.amazonaws.com \
            --statement-id s3invoke \
            --action "lambda:InvokeFunction" \
            --source-arn arn:aws:s3:::${DOC_BUCKET_NAME} \
            --source-account ${ACCOUNT_ID}
            
          echo "Configuring S3 notification..."
          aws s3api put-bucket-notification-configuration \
            --bucket "${DOC_BUCKET_NAME}" \
            --notification-configuration "{\"LambdaFunctionConfigurations\":[{\"LambdaFunctionArn\":\"${INGESTOR_FUNCTION_ARN}\",\"Events\":[\"s3:ObjectCreated:*\"]}]}"

  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    needs: deploy
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Import Step Function if exists
        run: |
          STATE_MACHINE_NAME="IngestorStateMachine"
          STATE_MACHINE_ARN=$(aws stepfunctions list-state-machines --query "stateMachines[?name=='$STATE_MACHINE_NAME'].stateMachineArn" --output text)
          TF_RESOURCE="aws_sfn_state_machine.state_machine"
          if [ -z "$STATE_MACHINE_ARN" ]; then
            echo "State machine $STATE_MACHINE_NAME does not exist, skipping import."
          else
            echo "Importing state machine: $STATE_MACHINE_ARN"
            terraform import $TF_RESOURCE $STATE_MACHINE_ARN || true
          fi

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
          if [ $? -ne 0 ]; then
            echo "Terraform apply failed, destroying resources"
            terraform destroy -auto-approve
            exit 1
          fi
