name: Deploy Terraform
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
    # paths:
    #   - 'terraform/**'
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Create tfvars file with bucket name from secret
        run: echo "bucket_name = \"${{ secrets.DOC_BUCKET_NAME }}\"" > override.tfvars

      - name: Terraform Plan
        run: terraform plan -var-file=override.tfvars

      - name: Terraform Apply
        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -var-file=override.tfvars